# .streamlit/secrets.toml
OPENAI_API_KEY = "sk-..."
GOOGLE_API_KEY = "AIzaSyBu2NpI_13toIDizmw7nEcum-PMRILoFKw"
ANTHROPIC_API_KEY = "sk-ant-..."
MISTRAL_API_KEY = "YourMistralKey..."
# Add others as needed (DEEPSEEK_API_KEY, META_API_KEY/GROQ_API_KEY etc.)
