# .streamlit/secrets.toml

OPENAI_API_KEY = "sk-..."
GOOGLE_API_KEY = "AIzaSyAFkM3idn_wPObWfSOZ6cUid8V1Ffi11eE"
ANTHROPIC_API_KEY = "sk-ant-..."
MISTRAL_API_KEY = "YourMistralKey..."

# Specific keys for each NVIDIA model
NVIDIA_Mistral_Small_24B_Instruct = "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" # Your actual key
NVIDIA_DeepSeek_R1_Distill_Qwen_32B = "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" # Your actual key (can be the same as above)

# Comment out or remove the generic DEEPSEEK_API / NVIDIA_API_KEY if present
# DEEPSEEK_API = "..."
# NVIDIA_API_KEY = "..."
