# .streamlit/secrets.toml
OPENAI_API_KEY = "sk-..."
GOOGLE_API_KEY = "AIzaSyAFkM3idn_wPObWfSOZ6cUid8V1Ffi11eE"
ANTHROPIC_API_KEY = "sk-ant-..."
MISTRAL_API_KEY = "YourMistralKey..."
DEEPSEEK_API = "sk-0e1729d4a6024523bbf9859b09a7fbcd"
# Add others as needed (DEEPSEEK_API_KEY, META_API_KEY/GROQ_API_KEY etc.)
